apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: search
    visualize: "true"
  name: search
spec:
  deprecatedPublicIPs:
  - 192.168.1.11
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    run: search
    visualize: "true"
status:
  loadBalancer: {}
