apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: contact
    visualize: "true"
  name: contact
spec:
  deprecatedPublicIPs:
  - 192.168.1.11
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 9003
    protocol: TCP
    targetPort: 9003
  selector:
    run: contact
    visualize: "true"
status:
  loadBalancer: {}
