apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: homepage
    visualize: "true"
  name: homepage
spec:
  deprecatedPublicIPs:
  - 192.168.1.11
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: homepage
    visualize: "true"
status:
  loadBalancer: {}
