apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: configserver
    visualize: "true"
  name: configserver
spec:
  deprecatedPublicIPs:
  - 192.168.1.11
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: configserver
    visualize: "true"
status:
  loadBalancer: {}
