apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: basket
    visualize: "true"
  name: basket
spec:
  deprecatedPublicIPs:
  - 192.168.1.11
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    run: basket
    visualize: "true"
status:
  loadBalancer: {}
