apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: basket
    visualize: "true"
  name: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      run: basket
      visualize: "true"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: basket
        visualize: "true"
    spec:
      containers:
      - image: bilalkais/basket
        name: basket
        resources: {}
status: {}
